name: ci

on:
  workflow_dispatch:
  push:
  # pull_request:
  # schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

env:
  GODOT_VERSION: 4.3-stable

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4

      - run: ls
      - run: ls Godottest
      - run: ls Godottest/res

      - name: checkout media
        uses: actions/checkout@v4
        with:
          repository: trevyn/media
          token: ${{ secrets.MEDIA_TOKEN }}
          path: Godottest/res/media

      - run: ls Godottest/res/media

      - run: curl -o templates.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_export_templates.tpz
      - run: unzip templates.zip templates/windows_release_x86_64.exe
      - run: mv templates/windows_release_x86_64.exe Godottest/Godottest.exe

      - name: install steamcmd
        run: |
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install steamcmd
          mkdir -p ~/Steam/config

      - run: echo "${{ secrets.STEAM_CONFIG_VDF }}" | base64 -d > ~/Steam/config/config.vdf
      - run: sed -i 's/STEAM_APP_ID/${{ secrets.STEAM_APP_ID }}/g' manifest.vdf
      - run: sed -i 's/STEAM_DEPOT/${{ secrets.STEAM_DEPOT }}/g' manifest.vdf
      - run: pwd
      - run: ls
      - run: ls Godottest
      - run: ls -la Godottest/res/media
      - run: rm -rf Godottest/res/media/.git
      - run: ls -la Godottest/res/media

      - run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build "$(pwd)/manifest.vdf" +quit
